import { AppData } from './storage';

export function generateReportHtml(data: AppData): string {
    const { university, degreeType, major, cgpa, semesters } = data;

    const title = [university, degreeType, major].filter(Boolean).join(' — ');
    const sorted = [...semesters].sort((a, b) => a.id - b.id);

    const semesterSections = sorted.map(sem => {
        const rows = sem.subjects.map(sub => `
      <tr>
        <td>${sub.name}</td>
        <td class="center">${sub.credit}</td>
        <td class="center">${sub.grade}</td>
      </tr>
    `).join('');

        return `
      <div class="semester">
        <div class="sem-header">
          <span class="sem-title">Semester ${sem.id}</span>
          <span class="sem-sgpa">SGPA: <strong>${sem.sgpa.toFixed(2)}</strong></span>
        </div>
        <table>
          <thead>
            <tr>
              <th>Subject Name</th>
              <th class="center">Credit Hours</th>
              <th class="center">Grade</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
        <div class="sem-footer">Total Credits: ${sem.totalCredits}</div>
      </div>
    `;
    }).join('');

    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Academic Report</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
      background: #f9fafb;
      color: #1a1a2e;
      padding: 40px 48px;
      font-size: 13px;
    }
    .report-header {
      text-align: center;
      margin-bottom: 36px;
      padding-bottom: 24px;
      border-bottom: 2px solid #e2e8f0;
    }
    .report-header h1 {
      font-size: 22px;
      font-weight: 900;
      color: #0f172a;
      letter-spacing: 0.5px;
    }
    .report-header p {
      font-size: 13px;
      color: #64748b;
      margin-top: 6px;
    }
    .semester {
      background: #ffffff;
      border: 1px solid #e2e8f0;
      border-radius: 12px;
      padding: 20px 24px;
      margin-bottom: 24px;
      page-break-inside: avoid;
    }
    .sem-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 14px;
    }
    .sem-title {
      font-size: 15px;
      font-weight: 800;
      color: #0f172a;
    }
    .sem-sgpa {
      font-size: 13px;
      color: #475569;
    }
    table {
      width: 100%;
      border-collapse: collapse;
    }
    thead tr {
      background: #f1f5f9;
    }
    th {
      padding: 9px 12px;
      text-align: left;
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.8px;
      color: #64748b;
    }
    td {
      padding: 10px 12px;
      border-top: 1px solid #f1f5f9;
      color: #334155;
      font-size: 13px;
    }
    .center { text-align: center; }
    .sem-footer {
      margin-top: 12px;
      font-size: 11px;
      color: #94a3b8;
      text-align: right;
    }
    .cgpa-block {
      background: #0f172a;
      color: #fff;
      border-radius: 12px;
      padding: 28px 32px;
      margin-top: 32px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .cgpa-label {
      font-size: 12px;
      font-weight: 700;
      letter-spacing: 1.5px;
      text-transform: uppercase;
      color: #94a3b8;
    }
    .cgpa-value {
      font-size: 40px;
      font-weight: 900;
      color: #ffffff;
      margin-top: 4px;
    }
    .cgpa-semesters {
      font-size: 13px;
      color: #64748b;
      text-align: right;
    }
    .generated {
      text-align: center;
      margin-top: 32px;
      font-size: 11px;
      color: #cbd5e1;
    }
  </style>
</head>
<body>
  <div class="report-header">
    <h1>${title || 'Academic Report'}</h1>
    <p>GPA Pro — Semester-wise Academic Report</p>
  </div>

  ${semesterSections}

  <div class="cgpa-block">
    <div>
      <div class="cgpa-label">Cumulative CGPA</div>
      <div class="cgpa-value">${cgpa.toFixed(2)}</div>
    </div>
    <div class="cgpa-semesters">${sorted.length} Semester${sorted.length !== 1 ? 's' : ''}<br/>Completed</div>
  </div>

  <div class="generated">Generated by GPAPro • ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
</body>
</html>
  `;
}
